import { UpgradeStage, UpgradeStageId } from '../types';

export const NOTHING_AI_UPGRADE_STAGES: Record<UpgradeStageId, UpgradeStage> = {
  1: {
    stage: 1,
    name: 'Stage 1: Basic Free',
    subtitle: 'Fast Essentials & Quick Facts',
    description: 'Instant response speed, essential factual lookups, definitions, and standard Q&A.',
    badgeColor: 'text-zinc-300 border-zinc-700 bg-zinc-800',
    badgeBg: 'bg-zinc-800',
    reasoningDepth: 'Basic Speed',
    maxTokens: 2048,
    modelAlias: 'Nothing-Ai Lite',
    contextWindow: '32K Tokens',
    features: [
      'Standard responses & definitions',
      'Basic formula lookups',
      'Access to Qorin & Nothing-Ai Core personas',
      'Web & CLI interface access',
    ],
  },

  2: {
    stage: 2,
    name: 'Stage 2: Standard Plus',
    subtitle: 'Enhanced Context & Extended Output',
    description: 'Increased context length, faster response times, and standard utility search optimizations.',
    badgeColor: 'text-zinc-200 border-zinc-700 bg-zinc-800',
    badgeBg: 'bg-zinc-800',
    reasoningDepth: 'Step-by-Step',
    maxTokens: 4096,
    modelAlias: 'Nothing-Ai Flash Core',
    contextWindow: '128K Tokens',
    features: [
      'Extended output limits (4,096 tokens)',
      'Web-search grounding capabilities',
      'Enhanced multi-turn conversation memory',
      'Standard model routing optimizations',
      'Direct markdown rendering and exports',
    ],
  },

  3: {
    stage: 3,
    name: 'Stage 3: Pro Creator',
    subtitle: 'Long-Form Content & Creative Writing',
    description: 'Expanded generation lengths for speeches, project reports, articles, and creative ideation.',
    badgeColor: 'text-zinc-200 border-zinc-700 bg-zinc-800',
    badgeBg: 'bg-zinc-800',
    reasoningDepth: 'High Reasoning',
    maxTokens: 8192,
    modelAlias: 'Nothing-Ai Flash Core',
    contextWindow: '256K Tokens',
    features: [
      'Extended output token limit (8,192 tokens)',
      'Article & Speech writing templates',
      'Unlocks Lyren, Qyra, Elion creative personas',
      'Markdown report export & formatting',
      'Color palette & UI wireframe generator',
    ],
  },

  4: {
    stage: 4,
    name: 'Stage 4: Pro Max Power User',
    subtitle: 'Deep Code & Technical Engineering',
    description: 'Pro Max reasoning for full-stack code implementation, bug fixing, and mathematical proofs.',
    badgeColor: 'text-zinc-200 border-zinc-700 bg-zinc-800',
    badgeBg: 'bg-zinc-800',
    reasoningDepth: 'Pro Max Deep',
    maxTokens: 16384,
    modelAlias: 'Nothing-Ai Pro Core',
    contextWindow: '1M Tokens',
    features: [
      'Full-stack code generation (Python, C++, React)',
      'Multi-file architectural specifications',
      'Calculus proofs & physics derivations',
      'Unlocks Valtis & Zorin power coding modes',
      'Code execution sandbox & debug tracing',
    ],
  },

  5: {
    stage: 5,
    name: 'Stage 5: Automation Agent',
    subtitle: 'Multi-Step Planning & Persona Routing',
    description: 'Agentic breakdown of complex tasks, automated verification pass, and multi-persona synthesis.',
    badgeColor: 'text-zinc-200 border-zinc-700 bg-zinc-800',
    badgeBg: 'bg-zinc-800',
    reasoningDepth: 'Agentic Planning',
    maxTokens: 32768,
    modelAlias: 'Nothing-Ai Pro Core',
    contextWindow: '1M Tokens',
    features: [
      'Automated multi-persona workflow routing',
      'Two-pass answer verification with Norix QA',
      'Complex project roadmap decomposition',
      'System design ER diagrams & DB schemas',
      'Full CLI command scripting engine',
    ],
  },

  6: {
    stage: 6,
    name: 'Stage 6: Apex Enterprise',
    subtitle: 'Maximum Reasoning & Unlimited Context',
    description: 'The highest tier of Nothing-Ai AI with unlimited reasoning simulation, top priority model execution, and zero restrictions.',
    badgeColor: 'text-zinc-200 border-zinc-700 bg-zinc-800',
    badgeBg: 'bg-zinc-800',
    reasoningDepth: 'Apex Reasoning',
    maxTokens: 65536,
    modelAlias: 'Nothing-Ai Apex Core',
    contextWindow: '2M Tokens',
    features: [
      'Maximum Nothing-Ai Apex reasoning depth',
      'All 10 Personas unlocked concurrently',
      'Unlimited local chat history & cloud export',
      'Priority server API streaming routing',
      'Desktop native application compilation specs',
    ],
  },
};

export const STAGE_LIST: UpgradeStage[] = Object.values(NOTHING_AI_UPGRADE_STAGES);
